/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  gengetopt -i cmdline.ggo

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: NBody [OPTIONS]...";

const char *gengetopt_args_info_description = "N-Body Simulation";

const char *gengetopt_args_info_help[] = {
  "  -h, --help               Print help and exit",
  "  -V, --version            Print version and exit",
  "  -N, --num-particles=INT  Maximum number of particles. The default value is \n                             only used\n                             	 when the input is random.  (default=`384')",
  "  -t, --num-timesteps=INT  Number of time-steps  (default=`1')",
  "  -e, --EPS=FLOAT          Damping factor  (default=`100')",
  "\n Group: input",
  "  -r, --random             Generate random input data",
  "  -f, --file=FILE          Read input data from file",
  "\n Group: platform",
  "  -c, --cpu                Run the simulation on the CPU only",
  "  -d, --dfe                Run the simulation on the DFE only",
  "  -m, --model              Use the model when running the DFE",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->num_particles_given = 0 ;
  args_info->num_timesteps_given = 0 ;
  args_info->EPS_given = 0 ;
  args_info->random_given = 0 ;
  args_info->file_given = 0 ;
  args_info->cpu_given = 0 ;
  args_info->model_given = 0 ;
  args_info->dfe_given = 0 ;
  args_info->input_group_counter = 0 ;
  args_info->platform_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->num_particles_arg = 384;
  args_info->num_particles_orig = NULL;
  args_info->num_timesteps_arg = 1;
  args_info->num_timesteps_orig = NULL;
  args_info->EPS_arg = 100;
  args_info->EPS_orig = NULL;
  args_info->file_arg = NULL;
  args_info->file_orig = NULL;

}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->num_particles_help = gengetopt_args_info_help[2] ;
  args_info->num_timesteps_help = gengetopt_args_info_help[3] ;
  args_info->EPS_help = gengetopt_args_info_help[4] ;
  args_info->random_help = gengetopt_args_info_help[6] ;
  args_info->file_help = gengetopt_args_info_help[7] ;
  args_info->cpu_help = gengetopt_args_info_help[9] ;
  args_info->dfe_help = gengetopt_args_info_help[10] ;
  args_info->model_help = gengetopt_args_info_help[11] ;

}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    {
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params =
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->num_particles_orig));
  free_string_field (&(args_info->num_timesteps_orig));
  free_string_field (&(args_info->EPS_orig));
  free_string_field (&(args_info->file_arg));
  free_string_field (&(args_info->file_orig));



  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->num_particles_given)
    write_into_file(outfile, "num-particles", args_info->num_particles_orig, 0);
  if (args_info->num_timesteps_given)
    write_into_file(outfile, "num-timesteps", args_info->num_timesteps_orig, 0);
  if (args_info->EPS_given)
    write_into_file(outfile, "EPS", args_info->EPS_orig, 0);
  if (args_info->random_given)
    write_into_file(outfile, "random", 0, 0 );
  if (args_info->file_given)
    write_into_file(outfile, "file", args_info->file_orig, 0);
  if (args_info->cpu_given)
    write_into_file(outfile, "cpu", 0, 0 );
  if (args_info->model_given)
    write_into_file(outfile, "model", 0, 0 );
  if (args_info->dfe_given)
    write_into_file(outfile, "dfe", 0, 0 );


  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_input(struct gengetopt_args_info *args_info)
{
  if (! args_info->input_group_counter)
    return;

  args_info->random_given = 0 ;
  args_info->file_given = 0 ;
  free_string_field (&(args_info->file_arg));
  free_string_field (&(args_info->file_orig));

  args_info->input_group_counter = 0;
}

static void
reset_group_platform(struct gengetopt_args_info *args_info)
{
  if (! args_info->platform_group_counter)
    return;

  args_info->cpu_given   = 0 ;
  args_info->model_given = 0 ;
  args_info->dfe_given   = 0 ;

  args_info->platform_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }

  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given,
               char *value, char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n",
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n",
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }


  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  int override;
  int initialize;
  int check_required;
  int check_ambiguity;

  package_name = argv[0];

  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "num-particles",	1, NULL, 'N' },
        { "num-timesteps",	1, NULL, 't' },
        { "EPS",	1, NULL, 'e' },
        { "random",	0, NULL, 'r' },
        { "file",	1, NULL, 'f' },
        { "cpu",	0, NULL, 'c' },
        { "dfe",	0, NULL, 'd' },
        { "model",	0, NULL, 'm' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVN:t:e:rf:cdm", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'N':	/* Maximum number of particles. The default value is only used
        	 when the input is random..  */


          if (update_arg( (void *)&(args_info->num_particles_arg),
               &(args_info->num_particles_orig), &(args_info->num_particles_given),
              &(local_args_info.num_particles_given), optarg, 0, "384", ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-particles", 'N',
              additional_error))
            goto failure;

          break;
        case 't':	/* Number of time-steps.  */


          if (update_arg( (void *)&(args_info->num_timesteps_arg),
               &(args_info->num_timesteps_orig), &(args_info->num_timesteps_given),
              &(local_args_info.num_timesteps_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-timesteps", 't',
              additional_error))
            goto failure;

          break;
        case 'e':	/* Damping factor.  */


          if (update_arg( (void *)&(args_info->EPS_arg),
               &(args_info->EPS_orig), &(args_info->EPS_given),
              &(local_args_info.EPS_given), optarg, 0, "100", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "EPS", 'e',
              additional_error))
            goto failure;

          break;
        case 'r':	/* Generate random input data.  */

          if (args_info->input_group_counter && override)
            reset_group_input (args_info);
          args_info->input_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->random_given),
              &(local_args_info.random_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "random", 'r',
              additional_error))
            goto failure;

          break;
        case 'f':	/* Read input data from file.  */

          if (args_info->input_group_counter && override)
            reset_group_input (args_info);
          args_info->input_group_counter += 1;

          if (update_arg( (void *)&(args_info->file_arg),
               &(args_info->file_orig), &(args_info->file_given),
              &(local_args_info.file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "file", 'f',
              additional_error))
            goto failure;

          break;
        case 'c':	/* Run the simulation on the CPU only.  */

          if (args_info->platform_group_counter && override)
            reset_group_platform (args_info);
          args_info->platform_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->cpu_given),
              &(local_args_info.cpu_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "cpu", 'c',
              additional_error))
            goto failure;

          break;
        case 'm':	/* Use the model when running the DFE  */

          if (args_info->platform_group_counter && override)
            reset_group_platform (args_info);
          args_info->platform_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->model_given),
              &(local_args_info.model_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "model", 'm',
              additional_error))
            goto failure;

          break;
        case 'd':	/* Run the simulation on the DFE only.  */

          if (args_info->platform_group_counter && override)
            reset_group_platform (args_info);
          args_info->platform_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->dfe_given),
              &(local_args_info.dfe_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "dfe", 'd',
              additional_error))
            goto failure;

          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->input_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group input were given. At most one is required.%s\n", argv[0], args_info->input_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }

  if (args_info->platform_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group platform were given. At most one is required.%s\n", argv[0], args_info->platform_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:

  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
